#!/bin/sh
# This script is used to make sure the floodlight stays on while the setting is on. It will set the brightness to the value every 15 seconds.

# This function takes a brightness percentage as an argument and returns the command string to set the brightness of the floodlight
get_floodlight_command_string() {
	initial_total=405
	brightness_pct=$1
	brightness_hex=$(printf "%02x" $((255*brightness_pct/100)))
	#echo "brightness_hex: ${brightness_hex}"
	brightness_dec=$((255*brightness_pct/100))
	sequence_start="\xaa\x55\x43\x06\x46"
	brightness_sequence="\x${brightness_hex}\x00\x07"
	combined_sequence="${sequence_start}${brightness_sequence}"
	# add brightness_dec and initial_total and print it as a 2 byte hex value in the format \x##\x##
	check_bytes_raw=$(printf "%.4x" $((${brightness_dec} + ${initial_total})))
	#echo "check_bytes_raw: ${check_bytes_raw}"
	# get the first 2 bytes of the check_bytes_raw using awk
	first_two_chars=$(echo $check_bytes_raw | awk '{print substr($0, 1, 2)}')
	# get the last 2 bytes of the check_bytes_raw using awk
	last_two_chars=$(echo $check_bytes_raw | awk '{print substr($0, 3, 2)}')
	# combine the first and last 2 bytes into a single string
	check_bytes="\x${first_two_chars}\x${last_two_chars}"
	echo -n "${combined_sequence}${check_bytes}"
}

# if there is no argument, print help
help() {
	echo "usage: floodlight_ctl_d"
}

# if the script is run with no args, display help
if [ $# -gt 0 ]; then
	echo "Invalid number of arguments"
	help
	exit 1
fi



# otherwise, set the brightness to the value every 15 seconds
while true; do
    # check if /var/run/floodlight.status exists and if so store it's value
    if [ -f /var/run/floodlight.status ]; then
        status=$(cat /var/run/floodlight.status)
    fi

    if [ "$status" == "ON" ] && [ -f /var/run/floodlight.brightness ]; then
        brightness_pct=$(cat /var/run/floodlight.brightness)
        brightness_string=$(get_floodlight_command_string $brightness_pct)
        echo "Setting brightness to $brightness_pct: [${brightness_string}]"
        echo -ne "${brightness_string}" > /dev/ttyUSB0
    fi
    if [ "$status" == "OFF" ]; then
        echo "Setting brightness to 0"
        brightness_string=$(get_floodlight_command_string 0)
        echo -ne "${brightness_string}" > /dev/ttyUSB0
    fi
	sleep 1
done

