#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $0 \"phrase to say\"
Shortcuts:
 %ip     Tell IP address
 %time   Tell recent time
"
	exit 1
fi

case "$1" in
	%ip)	phrase="IP address is $(ip r | grep -E 'wlan0|eth0' | grep src | awk '{ print $7 " for interface " $3 }')" ;;
	%time)	phrase="$(date)" ;;
	*)	phrase="$*" ;;
esac

curl --silent --get --url "https://thingino.com/say" --data-urlencode q="$phrase" | iac -s

exit 0
